mvignes-souksone/whats-for-dinner

app/models/menu.rb, config/puma.rb, db/migrate/20201123161846_add_column_names_to_users.rb, db/migrate/20201123162247_create_menus.rb, db/migrate/20201123162609_remove_column_user_id_from_menus.rb, db/migrate/20201123162829_add_user_id_to_menus.rb, db/schema.rb, test/models/menu_test.rb
New columns added to model user
and model menu created with migration
=> menu and user model and migration

app/models/recipe.rb, db/migrate/20201123162938_create_recipes.rb, db/migrate/20201123163344_add_column_names_to_recipe.rb, db/schema.rb, test/models/recipe_test.rb
Recipe Model creation (all columns)
=> model recipes

app/models/grocery_item.rb, app/models/ingredient.rb, db/migrate/20201123170634_create_ingredients.rb, db/migrate/20201123171416_create_grocery_items.rb, db/schema.rb, test/models/grocery_item_test.rb, test/models/ingredient_test.rb
=> temporary models

app/models/menu.rb, app/models/menu_recipe.rb, app/models/preparation.rb, app/models/review.rb, app/models/user.rb, db/migrate/20201123170144_create_menu_recipes.rb, db/migrate/20201123171018_create_preparations.rb, db/migrate/20201123171231_create_reviews.rb, db/schema.rb, test/models/menu_recipe_test.rb, test/models/preparation_test.rb, test/models/review_test.rb
=> model preparation and review without db:migrate

db/schema.rb
Db migrate coordination 
All tables are created except accesses
=> db migrate coordination

app/controllers/grocery_items_controller.rb, app/controllers/ingredients_controller.rb, app/controllers/menu_recipes_controller.rb, app/controllers/menus_controller.rb, app/controllers/preparations_controller.rb, app/controllers/recipes_controller.rb, app/controllers/reviews_controller.rb, app/controllers/users_controller.rb, app/models/ingredient.rb, app/models/menu.rb, app/models/menu_recipe.rb, app/models/recipe.rb, app/models/review.rb, app/models/user.rb, test/controllers/grocery_items_controller_test.rb, test/controllers/ingredients_controller_test.rb, test/controllers/menu_recipes_controller_test.rb, test/controllers/menus_controller_test.rb, test/controllers/preparations_controller_test.rb, test/controllers/recipes_controller_test.rb, test/controllers/reviews_controller_test.rb, test/controllers/users_controller_test.rb
Controllers updated with has_many and belongs_to 
but still missing has_one_attached photo
=> controllers created and has many and belongs to added in models

app/models/recipe.rb
has one attached photo added recipe
=> add relation has one attached photo

config/routes.rb
Routes creation and checked with teacher
=> Routes creation

app/models/grocery_item.rb, app/models/ingredient.rb, app/models/menu.rb, app/models/menu_recipe.rb, app/models/recipe.rb, app/models/review.rb
=> models modification

app/controllers/users_controller.rb, app/policies/grocery_item_policy.rb, app/policies/ingredient_policy.rb, app/policies/menu_policy.rb, app/policies/menu_recipe_policy.rb, app/policies/preparation_policy.rb, app/policies/recipe_policy.rb, app/policies/review_policy.rb, test/policies/grocery_item_policy_test.rb, test/policies/ingredient_policy_test.rb, test/policies/menu_policy_test.rb, test/policies/menu_recipe_policy_test.rb, test/policies/preparation_policy_test.rb, test/policies/recipe_policy_test.rb, test/policies/review_policy_test.rb
=> pundit controller installation

app/controllers/application_controller.rb, app/controllers/menus_controller.rb, app/models/recipe.rb, app/models/user.rb, app/policies/menu_policy.rb, app/views/devise/registrations/new.html.erb, app/views/menus/edit.html.erb, app/views/menus/new.html.erb, app/views/menus/show.html.erb
Création des méthodes dans le menus controller, des vues 
modfiication du model User et devise, pour pouvoir avoir dans le formulaire :username :last_name :first_name
=> Controller menus

app/controllers/menu_recipes_controller.rb, app/controllers/menus_controller.rb, app/policies/menu_recipe_policy.rb, app/views/menus/edit.html.erb
controller menu_recipes méthodes crées : 
- create
- destroy 
- update
sauf switch
=> controller menu recipes methodes crées sauf switch

app/controllers/menu_recipes_controller.rb
Modification destroy et update
=> modification destroy et update

app/controllers/grocery_items_controller.rb, app/policies/grocery_item_policy.rb, app/views/grocery_items/index.html.erb
Creation off the grocery_items controller
and creation of his index
=> controller Grocery Items et view index

app/controllers/grocery_items_controller.rb
=> PRIVATE devient private

app/assets/stylesheets/config/_fonts.scss
=> fonts setup

app/controllers/grocery_items_controller.rb, app/models/ingredient.rb, app/views/grocery_items/index.html.erb
Création de l'index Grocery_itms et addition des quantités pour un même grocery_item.
Et correction dans la CATEGORY (2 doublons enlevés).
=> Création de l'index Grocery_items addition des quantités

app/assets/stylesheets/pages/_home.scss, app/models/ingredient.rb, app/views/layouts/application.html.erb
rectification background home et categories
=> rectification background home et categories

db/seeds.rb
=> seed new modif

app/assets/stylesheets/components/_frames.scss, app/assets/stylesheets/components/_groceryitem.scss, app/assets/stylesheets/components/_index.scss, app/javascript/packs/application.js, app/views/grocery_items/index.html.erb
La liste de courses est affichée par rayon, rangé dans des box responsives.
cliquables mais pas encore rayable.
=> grocery items on going

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_groceryitem.scss, app/controllers/grocery_items_controller.rb, app/javascript/packs/application.js, app/models/grocery_item.rb, app/models/ingredient.rb, app/views/grocery_items/index.html.erb, config/routes.rb, db/migrate/20201126143953_remove_recipe_id_from_grocery_items.rb, db/schema.rb
Grocery list avec des checkbox
=> grocery-items-checkbox

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_frames.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/forms.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/controllers/menu_recipes_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/popovers.js, app/views/menus/edit.html.erb
=> Menu edit view

app/assets/stylesheets/components/_frames.scss, app/assets/stylesheets/pages/_menu_recipes.scss, app/views/menu_recipes/show.html.erb
modification de la menu recipe show apres revue avec l'équipe
=> modification de la menu recipe show apres revue avec l'équipe

app/views/layouts/application.html.erb
=> fix navbar menu

app/controllers/menus_controller.rb, app/models/menu.rb
concatenation of diet array into string
=> concatenation of diet array into string

app/views/menu_recipes/show.html.erb
=> stars in reviews display

app/assets/stylesheets/components/_footer.scss
=> footer responsive

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_frames.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/controllers/grocery_items_controller.rb, app/policies/grocery_item_policy.rb, app/views/menus/edit.html.erb, config/routes.rb
create_grocery method created and menu_recipes popovers CSS added
=> create_grocery method created and menu_recipes popovers CSS added

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_frames.scss, app/views/layouts/application.html.erb, app/views/menus/new.html.erb
=> fixing button

app/assets/stylesheets/components/_frames.scss
=> fix title menu recipe show

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_frames.scss, app/controllers/grocery_items_controller.rb, app/controllers/menu_recipes_controller.rb, app/controllers/menus_controller.rb, app/policies/menu_policy.rb, app/views/menus/show.html.erb, config/routes.rb
menu shox view done and create_menu_recipes method done for demo
=> menu shox view done and create_menu_recipes method done for demo

app/controllers/menu_recipes_controller.rb
=> fix menu recipe create

db/seeds.rb
=> seed modification

app/assets/stylesheets/components/_frames.scss, app/views/layouts/application.html.erb, db/seeds.rb
modif seed +grocery item + navbar
=> modif seed +grocery item + navbar

db/seeds.rb
=> Seed new recipes

app/controllers/menu_recipes_controller.rb
modification quantités menu recipe show
=> modification quantités menu recipe show

app/assets/stylesheets/components/_frames.scss, app/assets/stylesheets/components/_utilities.scss, app/assets/stylesheets/components/forms.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/views/pages/home.html.erb
Css modif small card recipe and illustrations
=> Css modif small card recipe

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_frames.scss
=> css menu recipe show

app/assets/stylesheets/components/_footer.scss, db/seeds.rb
=> seed destroy all Accesses

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_range.scss, app/assets/stylesheets/pages/_menu-new.scss, app/javascript/components/range.js, app/javascript/packs/application.js, app/javascript/plugins/display_review_form.js, app/views/grocery_items/index.html.erb, app/views/menus/new.html.erb, app/views/pages/home.html.erb
creating range on menu generation
=> range styling

app/assets/stylesheets/application.scss, app/javascript/packs/application.js, app/javascript/plugins/display_review_form.js, app/javascript/plugins/init_star_rating.js, app/views/menu_recipes/show.html.erb, package.json, yarn.lock
star rating formulaire review et affichage dans menu recipe
=> star rating formulaire review et affichage dans menu recipe

app/assets/stylesheets/pages/_menu_recipes.scss
=> object fit cover menu recipe photo

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_modal.scss, app/javascript/packs/application.js, app/views/grocery_items/index.html.erb
Modal en place pour ajouter un élément à la liste de course
=> grocery items modal done

app/assets/stylesheets/components/_frames.scss, app/assets/stylesheets/components/_utilities.scss, app/assets/stylesheets/components/forms.scss, app/controllers/grocery_items_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/tooltips.js, app/views/menus/show.html.erb
- Border added to the menu container
- alert added when going from menu edit view to the menu show view
- text giving more info about the menu added
- share button  style added
- share button tooltip added
=> menu show view done

app/controllers/accesses_controller.rb, app/controllers/menus_controller.rb, app/models/menu.rb, app/policies/menu_policy.rb, app/views/layouts/application.html.erb, app/views/menus/index.html.erb, config/routes.rb
History menus avec vue dégueulasse
=> History menus

app/assets/stylesheets/components/_frames.scss, app/views/menus/show.html.erb
css recipe done added to menu show view
=> css recipe done added

app/assets/stylesheets/pages/_menu_recipes.scss, app/controllers/menu_recipes_controller.rb, app/views/menu_recipes/show.html.erb, db/migrate/20201201084703_add_column_favorite_to_menu_recipes.rb, db/schema.rb
=> Add favorites

app/views/menu_recipes/show.html.erb, app/views/reviews/_new.html.erb
il y a maintenant 4 étoiles et non 5
=> display review fixing

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_index_menus.scss, app/controllers/menus_controller.rb, app/controllers/shared_menus_controller.rb, app/models/access.rb, app/views/layouts/application.html.erb, app/views/menus/index.html.erb, app/views/shared_menus/index.html.erb, config/routes.rb
=> history menus and shared menus

app/assets/stylesheets/components/_groceryitem.scss, app/views/grocery_items/index.html.erb
=> Grocery Items pencil fixed and four columns

app/assets/stylesheets/pages/_menu-new.scss, app/views/menus/_diet_card.html.erb
=> menu new icon size and title

app/controllers/reviews_controller.rb, app/models/review.rb
=> fix review

app/assets/stylesheets/components/_utilities.scss, app/views/menus/new.html.erb
margin top added to menu new view
=> margin top added to menu new view

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_groceryitem.scss, app/assets/stylesheets/components/_utilities.scss, app/assets/stylesheets/pages/_menu-new.scss, app/views/menus/show.html.erb
=> small mofifications in css

db/seeds.rb
image brick au thon : lien modifié dans seed
=> image brick au thon

public/404.html, public/500.html
=> personnalisation page 404 et 500

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_frames.scss, app/assets/stylesheets/components/_utilities.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_menu-new.scss, app/models/menu.rb, app/views/grocery_items/index.html.erb, app/views/menus/edit.html.erb, app/views/menus/new.html.erb, app/views/menus/show.html.erb, app/views/pages/home.html.erb
Modif css pour demo sur écran Caro.
+ modif model Menu pour que le last soit bien le last ;)
=> modif css pour demo

app/assets/stylesheets/components/_frames.scss, app/views/menus/index.html.erb, app/views/shared/_navbar.html.erb, app/views/shared_menus/index.html.erb
view index menu and shared menu done but small details still need to be added
=> view index menu and shared menu done 

app/assets/stylesheets/application.scss, app/controllers/ingredients_controller.rb, app/controllers/menus_controller.rb, app/controllers/preparations_controller.rb, app/controllers/recipes_controller.rb, app/javascript/components/init_select2.js, app/javascript/packs/application.js, app/policies/ingredient_policy.rb, app/policies/preparation_policy.rb, app/policies/recipe_policy.rb, app/views/recipes/edit.html.erb, app/views/recipes/new.html.erb, app/views/recipes/show.html.erb, config/routes.rb, package.json, yarn.lock
possibility to add a new recipe from url done
=> possibility to add a new recipe from url done

app/assets/stylesheets/components/_frames.scss, app/assets/stylesheets/pages/_menu_recipes.scss, app/controllers/menu_recipes_controller.rb, app/views/menu_recipes/show.html.erb
=> adding average rating

app/views/layouts/application.html.erb, app/views/menus/index.html.erb
=> bg picture

app/assets/stylesheets/components/_frames.scss, app/assets/stylesheets/components/forms.scss, app/views/menus/show.html.erb
=> Modif buttons menu show

app/assets/stylesheets/components/_modal.scss
Quelques petites corrections apportées en CSS sur la modal.
=> correction dans la modal de la grocery list

app/assets/stylesheets/components/_frames.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_menu-new.scss, app/assets/stylesheets/pages/_menu_recipes.scss, app/views/menus/new.html.erb
Responsive setup : home / new-menu / recipe-show / review
=> responsive home new-menu recipe-show review

app/controllers/menus_controller.rb, app/views/menus/index.html.erb, app/views/menus/show.html.erb
=> destroy redirection

app/assets/stylesheets/components/_frames.scss
=> button grocery in menu show fixing

app/controllers/menus_controller.rb
=> menu controller index

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_frames.scss, app/assets/stylesheets/components/forms.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/controllers/menu_recipes_controller.rb, app/controllers/menus_controller.rb, app/javascript/plugins/popovers.js, app/views/menus/edit.html.erb, app/views/shared_menus/_average_rating.html.erb
=> Modif menu edit

app/assets/stylesheets/components/_button.scss
arrow down display on smartphone
=> arrow down display

app/controllers/menu_recipes_controller.rb, app/views/menus/edit.html.erb
=> url problem in switch method

app/assets/stylesheets/components/forms.scss
=> modif send user button done

app/views/menus/show.html.erb
text above user share button done
=> text above user share button done

app/assets/stylesheets/components/_cards.scss, app/views/pages/home.html.erb, app/views/shared_menus/index.html.erb
=> small css changes
